### ISSUE TITLE
Peer-review Hindi storybooks

### ISSUE THREAD

**Issue by nya-elimu** [elimu-ai/wiki#101]
- [x] Level 1. Beginning to Read
- [x] Level 2. Learning to Read
- [x] Level 3. Reading Independently
- [x] Level 4. Reading Proficiently

Go through each storybook that is pending a peer-review at http://hin.elimu.ai/content/storybook/peer-reviews and look for incorrect words/translations. When you find an error, scroll down to "Peer review" and mark the storybook as _not approved_. If everything looks good, mark it as approved.

If a storybook is marked as not quality-approved, include a comment explaining why.

---

A list of all storybooks can be seen at http://hin.elimu.ai/content/storybook/list

**Comment by nya-elimuai** [comment]
@Jainanuradha Note that this task does not involve making any corrections to wrong translations/words. The task is only to mark the storybook as quality-approved or not.

**Comment by nya-elimuai** [comment]
@hacharya Can this issue be closed?
