### ISSUE TITLE
Develop literacy app: Storybook reader

### ISSUE THREAD

**Issue by nya-elimu** [elimu-ai/wiki#66]
See https://github.com/elimu-ai/vitabu/projects

- [x] https://github.com/elimu-ai/vitabu/issues/23
- [x] https://github.com/elimu-ai/vitabu/issues/25
- [x] https://github.com/elimu-ai/vitabu/issues/26
- [x] https://github.com/elimu-ai/vitabu/issues/28
- [x] https://github.com/elimu-ai/vitabu/issues/35
- [x] https://github.com/elimu-ai/vitabu/issues/44
- [x] https://github.com/elimu-ai/vitabu/issues/45
- [x] https://github.com/elimu-ai/vitabu/issues/48
- [x] https://github.com/elimu-ai/vitabu/issues/53
- [x] https://github.com/elimu-ai/vitabu/issues/57
- [x] https://github.com/elimu-ai/vitabu/issues/61
- [x] https://github.com/elimu-ai/vitabu/issues/62
- [x] https://github.com/elimu-ai/vitabu/issues/67
- [x] https://github.com/elimu-ai/vitabu/issues/73
- [x] https://github.com/elimu-ai/vitabu/issues/77
- [x] https://github.com/elimu-ai/vitabu/issues/85
- [x] https://github.com/elimu-ai/vitabu/issues/66
- [x] https://github.com/elimu-ai/vitabu/issues/58
- [ ] https://github.com/elimu-ai/vitabu/issues/90
- [ ] https://github.com/elimu-ai/vitabu/issues/64

**Comment by nya-elimuai** [comment]
@gscdev Your [$ELIMU 💎](https://etherscan.io/token/0xe29797910d413281d2821d5d9a989262c8121cc2) token rewards: https://etherscan.io/tx/0xe2ef46ba1b6213cff996f5fa5a7faf7263b0813e682afdba16c37388331883de

<img width="633" alt="Screen Shot 2021-12-18 at 6 48 04 PM" src="https://user-images.githubusercontent.com/15718174/146645331-03201f82-bec5-4649-944b-8efec40df548.png">
