### ISSUE TITLE
Make it easier for contributors to  add and peer review audio recordings

### ISSUE THREAD

**Issue by nya-elimuai** [elimu-ai/wiki#85]
See https://github.com/elimu-ai/webapp/projects/6

- [x] https://github.com/elimu-ai/webapp/projects/6#card-58548810
- [x] https://github.com/elimu-ai/webapp/projects/6#card-60517183
- [x] https://github.com/elimu-ai/webapp/projects/6#card-60869073

**Comment by UmenR** [comment]
Closing this issue with the completion of https://github.com/elimu-ai/webapp/projects/6#card-60869073
