### ISSUE TITLE
Develop REST API for the Crowdsource app

### ISSUE THREAD

**Issue by nya-elimu** [elimu-ai/wiki#86]
- [ ] https://github.com/elimu-ai/webapp/issues/1094

**Comment by nya-elimuai** [comment]
@UmenR Your [$ELIMU 💎](https://etherscan.io/token/0xe29797910d413281d2821d5d9a989262c8121cc2) token rewards: https://etherscan.io/tx/0xe2ef46ba1b6213cff996f5fa5a7faf7263b0813e682afdba16c37388331883de

<img width="633" alt="Screen Shot 2021-12-18 at 6 48 04 PM" src="https://user-images.githubusercontent.com/15718174/146645331-03201f82-bec5-4649-944b-8efec40df548.png">

**Comment by nya-elimuai** [comment]
@UmenR Your $ELIMU 💎 token rewards: https://etherscan.io/tx/0x3fc9bcf7cd34bb2339893ae609bb9aa34a0526c932d18072da9a02f925e5cc0f
