### ISSUE TITLE
Improve input-validation for words

### ISSUE THREAD

**Issue by nya-elimuai** [elimu-ai/wiki#96]
Implement measures to prevent contributors from storing invalid words.

- [x] https://github.com/elimu-ai/webapp/issues/1366
- [x] https://github.com/elimu-ai/webapp/issues/420

**Comment by nya-elimuai** [comment]
@watr-sheep Hi, Sandun. Do you need assistance with this?

**Comment by watr-sheep** [comment]
> @watr-sheep Hi, Sandun. Do you need assistance with this?

@nya-elimuai Not really, actually I couldn't look into the issue as I was busy for the past few days. I'll take a look today and will inform you if I need any help with it. Thanks.
